name: CI

on:
  push:
  pull_request:
    branches: [master]
  schedule:
    - cron: '0 6 * * 6'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        project: [molek-syntez, opus-magnum, picross-touch, shenzhen-io]
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ${{matrix.project}}
    env:
      SHARDS_OPTS: --ignore-crystal-version
    steps:
      - name: Download source
        uses: actions/checkout@v2
      - name: Install Crystal
        uses: oprypin/install-crystal@v1
        with:
          shards: nightly

      - name: Install dependencies
        run: shards install
      - name: Build
        run: shards build
